name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npm run export
      - name: Deploy to Netlify
        uses: netlify/actions/deploy@main
        with:
          access_token: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_ref: ${{ github.ref }}
          github_sha: ${{ github.sha }}
